name: CI to Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches: 
      - main
      - development

# on:
#   push:
#     branches:
#       - main
#       - development
#     types: [opened, synchronize, closed]
#   pull_request:
#     branches:
#       - main
#       - development
#     types: [opened, synchronize, closed]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
#        if: github.event.pull_request.merged == true
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/PKamnani/pk-devops-aap-ee
            azure-pipeline-name: 'pkamnani.test-azure-pipeline'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}