name: CI to Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - development
    types: [synchronize]
  pull_request:
    branches: 
      - main
    types: [synchronize]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/PKamnani/pk-devops-aap-ee
            azure-pipeline-name: 'pkamnani.test-azure-pipeline'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}